### ISSUE TITLE
Class 'Tunnel' incorrectly implements interface 'Url'

### ISSUE THREAD

**Issue by igor-urdenko** [theintern/digdug#78]
When I run `npm install` on fresh copy of the project at my work and then try to compile it I receive the following error:

```
node_modules/@theintern/digdug/Tunnel.d.ts:6:22 - error TS2420: Class 'Tunnel' incorrectly implements interface 'Url'.
  Type 'Tunnel' is missing the following properties from type 'Url': hash, host, href, path, and 3 more.

6 export default class Tunnel extends Evented<TunnelEvents, string> implements TunnelProperties, Url {
                       ~~~~~~


Found 1 error.
```

The only workaround I found is manually add the following properties into Tunnel.d.ts:
```
    hash: string;
    host: string;
    href: string;
    path: string;
    search: string;
    slashes: boolean;
    query: string;
```
That is not the correct way of resolving that of course, but I can't find any better. I am new to Typescript, and therefore it is possible that I do something wrong.

Could you please advise?

**Comment by jason0x43** [comment]
What definition are you using for `Url`? If you're in VScode, or something else that lets you jump to declarations, jump to the declaration of Url. It should be in `@types/node`. In that definition of Url, `hash`, `host`, etc. are optional.

**Comment by igor-urdenko** [comment]
The compilation works without errors if I add a direct dependency to `@types/node 10.17.1` in my `package.json`

**Comment by jason0x43** [comment]
Ah, ok. Intern includes `@types/node` as a devDependency rather than a dependency (having it as a dependency has caused issues in the past), so if nothing else was bringing it in, TS may have been defaulting to the DOM version of URL.

**Comment by igor-urdenko** [comment]
Should I close the issue?

**Comment by jason0x43** [comment]
Yes, please, if the issue seems to be sufficiently resolved

**Comment by jason0x43** [comment]
Or I can just click the wrong button...

**Comment by jason0x43** [comment]
I can reopen if it's not sufficiently resolved 😄

**Comment by EdenTurgeman** [comment]
I'm having the same issue and having a hard time understanding what the issue was and how it is fixed, upgraded some dependencies and it suddenly poped up.

**Comment by jason0x43** [comment]
The issue is that the typing for Url changed in the node 12 typings. Tunnel currently implements the pre-node 12 Url type, so if your project is using node 12 typings you may see this error.

Reopening this, and redirecting theintern/intern#999 here.

**Comment by jason0x43** [comment]
I just published digdug 2.4.2, which updates Tunnel to not explicitly implement Url (there's not actually a need for it to implement Url). Reinstall Intern (or just update `@theintern/digdug`) and see if that works better.

**Comment by igor-urdenko** [comment]
I tried to update Intern and the issue is still present:
![issue-tunnel](https://user-images.githubusercontent.com/32652656/70535538-43027680-1b2b-11ea-80e2-fbf878200ce6.png)

**Comment by jason0x43** [comment]
It looks like digdug didn't update. What do you get with `npm ls @theintern/digdug`? If it's still an older version (not 2.4.2), try removing your package and/or yarn lock files, or removing the entries for digdug from those files, and reinstall Intern.

**Comment by igor-urdenko** [comment]
![Screen Shot 2019-12-10 at 16 42 46](https://user-images.githubusercontent.com/32652656/70571636-38b49c80-1b6c-11ea-9f2d-ef36c886c4db.png)
I do not use digdug directly. It is used by intern and I use 'latest' intern

**Comment by jason0x43** [comment]
Intern depends on `~@theintern/digdug`, so it will pick up new patch versions. However, if you’re re-installing a package in a directory where you have a lock file, you’ll get the versions of dependencies in the lock file, which will be what was available when the package was first installed.

Clearing the lock file and reinstalling dependencies will ensure that all dependencies are up to date. Alternatively, you should be able to update just the digdug dependency with

```
npm update --depth 2 @theintern/digdug
```

**Comment by igor-urdenko** [comment]
Yes, that worked. Thank you!
